// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/chat" | "/create" | "/dashboard" | "/earn" | "/r/[code]" | "/settings" | "/staking" | "/staking-onchain" | "/treasury"
type AppRouteHandlerRoutes = "/api/admin" | "/api/anon" | "/api/api-keys" | "/api/auth/callback" | "/api/credits" | "/api/credits/check-deposit" | "/api/images/generate" | "/api/node-bind" | "/api/plan" | "/api/profile" | "/api/profile/delete" | "/api/profile/increment-prompts" | "/api/profile/link-wallet" | "/api/profile/refresh-balance" | "/api/referrals" | "/api/rpc" | "/api/staking/autocompound" | "/api/staking/claim-rewards" | "/api/staking/migrate" | "/api/staking/onchain-status" | "/api/staking/stats" | "/api/staking/status" | "/api/staking/unstake" | "/api/treasury" | "/api/treasury/history" | "/api/usage" | "/api/v1/balance" | "/api/v1/chat/completions" | "/api/v1/images/generations" | "/api/v1/models" | "/api/worker-earnings" | "/api/worker-payout" | "/api/worker-stats" | "/api/worker-token" | "/api/worker-wallet"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = "/user" | "/worker"
type RewriteRoutes = "/roadmap"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/admin": {}
  "/api/anon": {}
  "/api/api-keys": {}
  "/api/auth/callback": {}
  "/api/credits": {}
  "/api/credits/check-deposit": {}
  "/api/images/generate": {}
  "/api/node-bind": {}
  "/api/plan": {}
  "/api/profile": {}
  "/api/profile/delete": {}
  "/api/profile/increment-prompts": {}
  "/api/profile/link-wallet": {}
  "/api/profile/refresh-balance": {}
  "/api/referrals": {}
  "/api/rpc": {}
  "/api/staking/autocompound": {}
  "/api/staking/claim-rewards": {}
  "/api/staking/migrate": {}
  "/api/staking/onchain-status": {}
  "/api/staking/stats": {}
  "/api/staking/status": {}
  "/api/staking/unstake": {}
  "/api/treasury": {}
  "/api/treasury/history": {}
  "/api/usage": {}
  "/api/v1/balance": {}
  "/api/v1/chat/completions": {}
  "/api/v1/images/generations": {}
  "/api/v1/models": {}
  "/api/worker-earnings": {}
  "/api/worker-payout": {}
  "/api/worker-stats": {}
  "/api/worker-token": {}
  "/api/worker-wallet": {}
  "/chat": {}
  "/create": {}
  "/dashboard": {}
  "/earn": {}
  "/r/[code]": { "code": string; }
  "/roadmap": {}
  "/settings": {}
  "/staking": {}
  "/staking-onchain": {}
  "/treasury": {}
  "/user": {}
  "/worker": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
