// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat">> = Specific
  const handler = {} as typeof import("../../app/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create">> = Specific
  const handler = {} as typeof import("../../app/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/earn/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/earn">> = Specific
  const handler = {} as typeof import("../../app/earn/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/r/[code]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/r/[code]">> = Specific
  const handler = {} as typeof import("../../app/r/[code]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/staking-onchain/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staking-onchain">> = Specific
  const handler = {} as typeof import("../../app/staking-onchain/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/staking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staking">> = Specific
  const handler = {} as typeof import("../../app/staking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/treasury/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/treasury">> = Specific
  const handler = {} as typeof import("../../app/treasury/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin">> = Specific
  const handler = {} as typeof import("../../app/api/admin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/anon/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/anon">> = Specific
  const handler = {} as typeof import("../../app/api/anon/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/api-keys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/api-keys">> = Specific
  const handler = {} as typeof import("../../app/api/api-keys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/callback">> = Specific
  const handler = {} as typeof import("../../app/api/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/credits/check-deposit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/credits/check-deposit">> = Specific
  const handler = {} as typeof import("../../app/api/credits/check-deposit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/credits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/credits">> = Specific
  const handler = {} as typeof import("../../app/api/credits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/images/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/images/generate">> = Specific
  const handler = {} as typeof import("../../app/api/images/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/node-bind/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/node-bind">> = Specific
  const handler = {} as typeof import("../../app/api/node-bind/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plan">> = Specific
  const handler = {} as typeof import("../../app/api/plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/profile/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/delete">> = Specific
  const handler = {} as typeof import("../../app/api/profile/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/profile/increment-prompts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/increment-prompts">> = Specific
  const handler = {} as typeof import("../../app/api/profile/increment-prompts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/profile/link-wallet/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/link-wallet">> = Specific
  const handler = {} as typeof import("../../app/api/profile/link-wallet/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/profile/refresh-balance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/refresh-balance">> = Specific
  const handler = {} as typeof import("../../app/api/profile/refresh-balance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile">> = Specific
  const handler = {} as typeof import("../../app/api/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/referrals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/referrals">> = Specific
  const handler = {} as typeof import("../../app/api/referrals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rpc/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rpc">> = Specific
  const handler = {} as typeof import("../../app/api/rpc/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staking/autocompound/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staking/autocompound">> = Specific
  const handler = {} as typeof import("../../app/api/staking/autocompound/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staking/claim-rewards/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staking/claim-rewards">> = Specific
  const handler = {} as typeof import("../../app/api/staking/claim-rewards/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staking/migrate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staking/migrate">> = Specific
  const handler = {} as typeof import("../../app/api/staking/migrate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staking/onchain-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staking/onchain-status">> = Specific
  const handler = {} as typeof import("../../app/api/staking/onchain-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staking/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staking/stats">> = Specific
  const handler = {} as typeof import("../../app/api/staking/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staking/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staking/status">> = Specific
  const handler = {} as typeof import("../../app/api/staking/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staking/unstake/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staking/unstake">> = Specific
  const handler = {} as typeof import("../../app/api/staking/unstake/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/treasury/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/treasury/history">> = Specific
  const handler = {} as typeof import("../../app/api/treasury/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/treasury/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/treasury">> = Specific
  const handler = {} as typeof import("../../app/api/treasury/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/usage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/usage">> = Specific
  const handler = {} as typeof import("../../app/api/usage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/balance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/balance">> = Specific
  const handler = {} as typeof import("../../app/api/v1/balance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/chat/completions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/chat/completions">> = Specific
  const handler = {} as typeof import("../../app/api/v1/chat/completions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/images/generations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/images/generations">> = Specific
  const handler = {} as typeof import("../../app/api/v1/images/generations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/models/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/models">> = Specific
  const handler = {} as typeof import("../../app/api/v1/models/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/worker-earnings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/worker-earnings">> = Specific
  const handler = {} as typeof import("../../app/api/worker-earnings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/worker-payout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/worker-payout">> = Specific
  const handler = {} as typeof import("../../app/api/worker-payout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/worker-stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/worker-stats">> = Specific
  const handler = {} as typeof import("../../app/api/worker-stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/worker-token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/worker-token">> = Specific
  const handler = {} as typeof import("../../app/api/worker-token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/worker-wallet/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/worker-wallet">> = Specific
  const handler = {} as typeof import("../../app/api/worker-wallet/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
