var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/callback/route.js")
R.c("server/chunks/[root-of-the-server]__a8a9b254._.js")
R.c("server/chunks/lib_db_ts_033a32e3._.js")
R.c("server/chunks/[root-of-the-server]__f408c708._.js")
R.c("server/chunks/node_modules_@noble_curves_8b603fa7._.js")
R.c("server/chunks/node_modules_node-fetch-native_dist_node_mjs_558d0a9c._.js")
R.c("server/chunks/_d08b9ff6._.js")
R.c("server/chunks/node_modules_eb70c2c4._.js")
R.c("server/chunks/[root-of-the-server]__98d6514a._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_callback_route_actions_66c10d83.js")
R.m(265771)
module.exports=R.m(265771).exports
