import LegalPage from '@/components/legal/LegalPage';
import { pageMetadata } from '@/lib/page-title';

export async function generateMetadata() {
  return {
    ...(await pageMetadata('Terms', 'Terms of Service')),
    description: 'The agreement between you and Compute Network Inc.',
  };
}

export default function Terms() {
  return (
    <LegalPage title="Terms of Service" updated="10 AUGUST 2026">
      <p>
        These terms govern your use of the website, API, and network operated by{' '}
        <strong>Compute Network Inc.</strong>, a Delaware corporation (&ldquo;Compute Network&rdquo;,
        &ldquo;we&rdquo;). By creating an account, sending a request, or contributing compute, you agree to them.
      </p>

      <h2>1. Two ways to use the network</h2>
      <p>The service has two sides, and different parts of these terms apply to each.</p>
      <ul>
        <li>A <strong>requester</strong> sends prompts and pays in credits.</li>
        <li>A <strong>contributor</strong> runs a worker, serves requests with their own hardware, and earns.</li>
      </ul>
      <p>You may be both. Sections 3 to 5 concern requesters; section 6 concerns contributors.</p>

      <h2>2. Eligibility and accounts</h2>
      <p>You must be at least 18 years old and legally able to enter a contract. You are responsible for activity under your account and for keeping your API keys secret. Tell us promptly if a key is exposed.</p>

      <h2>3. Credits and payment</h2>
      <p>Access is prepaid using credits. Credits are denominated against United States dollars and are consumed as you use the service. Prices for each tier are shown in the application and may change; a change never alters credits you have already bought.</p>
      <p>Credits are a prepaid balance for using this service. They are not a deposit, not an investment, not a stored-value instrument, and cannot be transferred between accounts or exchanged for cash except as described in section 4.</p>

      <h2>4. Refunds</h2>
      <p>If a request fails, is not delivered, or is interrupted before completion, the credits for it are returned to your balance automatically. That is the ordinary remedy and it is applied without you needing to ask.</p>
      <p>For unused credits, contact us within 30 days of purchase and we will refund the unused balance to the payment method or wallet used, less any network transaction costs. We do not refund credits that have already been spent on completed requests, since the compute was performed and the contributor was paid for it.</p>

      <h2>5. Model output</h2>
      <p>Output is generated by machine learning models and is provided <strong>as is</strong>. It may be inaccurate, offensive, out of date, or plainly wrong. It is not professional advice of any kind. You are responsible for reviewing output before relying on it, and for how you use it.</p>
      <p>As between you and us, you own your prompts and the output produced for you, and you grant us only the limited licence needed to route, serve and bill your request.</p>
      <p>Your use of the service is subject to the <a href="/acceptable-use">Acceptable Use Policy</a>, which forms part of these terms.</p>

      <h2>6. Contributing compute</h2>
      <p>If you run a worker, you do so as an independent operator. You are not our employee, agent, or partner, and nothing here creates a joint venture. You are responsible for your own hardware, electricity, connectivity, and for any taxes on what you earn.</p>
      <p>Earnings accrue as a share of the value of requests your worker actually completes, at the rate shown in the application. We may withhold or reverse earnings that result from fraud, from returning fabricated or degraded output, or from manipulating the measurement of your work.</p>
      <p>The network runs automated integrity checks, including probe requests indistinguishable from ordinary jobs, coherence and throughput measurement. Failing these accumulates strikes against your worker identity, and enough strikes permanently bars the account from contributing. Strikes persist across sessions and reconnecting does not clear them. Barring an account from contributing does not remove its ability to use the service as a requester.</p>
      <p>Payouts are made in USDC on Solana to the wallet you nominate. You are responsible for the accuracy of that address. Transactions on a public blockchain are irreversible and we cannot recover funds sent to an address you gave us in error.</p>

      <h2>7. Availability</h2>
      <p>The network is made of machines contributed by independent people. Capacity varies, and we do not promise that any model, tier, or level of throughput will be available at a given moment. We may change, suspend, or discontinue parts of the service.</p>

      <h2>8. Suspension and termination</h2>
      <p>We may suspend or terminate an account that breaches these terms or the Acceptable Use Policy, that we reasonably believe is engaged in fraud, or where we are required to by law. You may close your account at any time. Unused credits remain refundable under section 4 unless the account was terminated for fraud.</p>

      <h2>9. Digital assets</h2>
      <p>Any token associated with the project is separate from the service described in these terms. Nothing here is an offer to sell, or a solicitation to buy, any token or security, and nothing here promises that any token will have value or utility. Using this service does not require holding any token.</p>

      <h2>10. Disclaimers and liability</h2>
      <p>The service is provided as is and as available, without warranties of any kind to the fullest extent the law allows, including any implied warranty of merchantability, fitness for a particular purpose, or non-infringement.</p>
      <p>To the fullest extent permitted by law, our total liability arising out of or relating to the service is limited to the greater of one hundred United States dollars or the amount you paid us in the three months before the event giving rise to the claim. We are not liable for indirect, incidental, special, consequential, or punitive damages, or for lost profits or data.</p>
      <p>Nothing in these terms limits liability that cannot lawfully be limited.</p>

      <h2>11. Indemnity</h2>
      <p>You agree to indemnify Compute Network Inc. against claims, losses and reasonable legal costs arising from your use of the service in breach of these terms or the Acceptable Use Policy.</p>

      <h2>12. Governing law</h2>
      <p>These terms are governed by the laws of the State of Delaware, United States, without regard to its conflict of laws rules. The state and federal courts located in Delaware have exclusive jurisdiction, and you and we consent to that jurisdiction.</p>

      <h2>13. Changes</h2>
      <p>We may update these terms. If a change materially affects your rights we will give notice in the application before it takes effect. Continuing to use the service after that constitutes acceptance.</p>

      <h2>14. Contact</h2>
      <p>
        Compute Network Inc.<br />
        <a href="mailto:legal@compute.tech">legal@compute.tech</a>
      </p>
    </LegalPage>
  );
}
