var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/profile/link-wallet/route.js")
R.c("server/chunks/[root-of-the-server]__8f4ea41a._.js")
R.c("server/chunks/lib_db_ts_033a32e3._.js")
R.c("server/chunks/[root-of-the-server]__f408c708._.js")
R.c("server/chunks/node_modules_@noble_curves_f0d6bc03._.js")
R.c("server/chunks/node_modules_node-fetch-native_dist_node_mjs_558d0a9c._.js")
R.c("server/chunks/node_modules_eb70c2c4._.js")
R.c("server/chunks/_d08b9ff6._.js")
R.c("server/chunks/[root-of-the-server]__98d6514a._.js")
R.c("server/chunks/_next-internal_server_app_api_profile_link-wallet_route_actions_a6a3cce9.js")
R.m(101449)
module.exports=R.m(101449).exports
