var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/staking/status/route.js")
R.c("server/chunks/_38ee8dd5._.js")
R.c("server/chunks/[root-of-the-server]__33368af6._.js")
R.c("server/chunks/[root-of-the-server]__f408c708._.js")
R.c("server/chunks/node_modules_fddf60a1._.js")
R.c("server/chunks/[root-of-the-server]__98d6514a._.js")
R.c("server/chunks/node_modules_eb70c2c4._.js")
R.c("server/chunks/_d08b9ff6._.js")
R.c("server/chunks/node_modules_node-fetch-native_dist_node_mjs_558d0a9c._.js")
R.c("server/chunks/node_modules_@noble_curves_f0d6bc03._.js")
R.c("server/chunks/_next-internal_server_app_api_staking_status_route_actions_5973f76d.js")
R.m(521745)
module.exports=R.m(521745).exports
