var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/v1/chat/completions/route.js")
R.c("server/chunks/[root-of-the-server]__ce97965f._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_dca48f12.js")
R.c("server/chunks/node_modules_b303ffd8._.js")
R.c("server/chunks/lib_db_ts_033a32e3._.js")
R.c("server/chunks/[root-of-the-server]__f408c708._.js")
R.c("server/chunks/node_modules_85c51dc2._.js")
R.c("server/chunks/[root-of-the-server]__98d6514a._.js")
R.c("server/chunks/node_modules_@noble_curves_8b603fa7._.js")
R.c("server/chunks/_next-internal_server_app_api_v1_chat_completions_route_actions_8366fb4b.js")
R.m(450079)
module.exports=R.m(450079).exports
