#!/usr/bin/env bash
#
# Build the compute.tech copies of the four static subdomains.
#
# docs/blog/data/shard.compute.tech used to share document roots with their
# c0mpute.ai twins, so any rebrand edit hit both domains. This script instead
# regenerates a Compute Network-branded copy of each site from the c0mpute.ai
# source, into /var/www/compute.tech/<site>, which is what the compute.tech
# server blocks in /etc/nginx/sites-available/compute.tech point at.
#
# The c0mpute.ai sources are read-only here. Nothing this script does can change
# the bytes docs/blog/data/shard.c0mpute.ai serve — re-run it as often as you
# like. Re-run it whenever one of those sources changes; the outputs are derived
# artifacts and are not tracked in git.
#
# Live data (data-site/stats.json, network.json) is symlinked rather than
# copied, so the generated sites keep showing current numbers between builds.
# Those symlinks are READ-ONLY BY CONVENTION: they point back into the
# c0mpute.ai sources, so anything that WRITES to
# /var/www/compute.tech/{data,shard}/*.json writes through into data.c0mpute.ai
# and shard.c0mpute.ai. Generators must keep writing to the c0mpute.ai paths
# and let the links follow.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REBRAND="$REPO/scripts/rebrand-compute-tech.py"

DOCS_SRC="$REPO/docs-site"
BLOG_SRC="$(dirname "$REPO")/c0mpute-blog"
DATA_SRC="$REPO/data-site"
SHARD_SRC="/var/www/shard.c0mpute.ai"
# Canonical checkout: where the live-data jobs write, regardless of which tree
# this script is invoked from.
#
# This is a COUPLING, not a convenience. c0mpute-networkmap and c0mpute-datastats
# are deliberately left running on the development checkout while orchestrator,
# web and keeper are pinned to /srv/c0mpute/prod, and their scripts anchor output
# to their own location rather than the working directory. So this path is only
# correct while those two units stay put. If either is ever repointed at the prod
# tree, its output moves with it and this goes stale — data.compute.tech would
# then serve a dangling symlink and no stats. Move this in the same change, or
# leave those two units where they are. See scripts/deploy.sh for the other half.
LIVE_DATA="/root/.openclaw/workspace/c0mpute/data-site"

OUT="/var/www/compute.tech"

mkdir -p "$OUT"

# ── docs.compute.tech ────────────────────────────────────────────────────────
# Rebrand the markdown into a generated mirror, then build Docusaurus against
# it. Filenames are preserved, so /why-c0mpute and /c0mpute-code keep their
# routes; only the prose inside changes.
echo "==> docs"
python3 "$REBRAND" "$DOCS_SRC/docs" "$DOCS_SRC/.docs-compute"
cd "$DOCS_SRC"
DOCS_CONTENT_DIR=.docs-compute \
DOCS_BRAND="Compute Network" \
DOCS_WORDMARK="Compute Network" \
  DOCS_HOME_HREF="https://compute.tech" \
  DOCS_APP_HREF="" \
DOCS_URL="https://docs.compute.tech" \
DOCS_BASE_URL=/ \
  DOCS_COLOR_MODE=dark \
  DOCS_FAVICON=img/favicon.svg \
  DOCS_TITLE="Compute Network / Docs" \
  npx docusaurus build --out-dir "$OUT/docs"

# ── blog.compute.tech ────────────────────────────────────────────────────────
echo "==> blog"
python3 "$REBRAND" "$BLOG_SRC" "$OUT/blog"

# ── data.compute.tech ────────────────────────────────────────────────────────
echo "==> data"
python3 "$REBRAND" "$DATA_SRC" "$OUT/data"
# These two are LIVE data, regenerated by the orchestrator into the canonical
# checkout — they are not build output. Symlinking them via $DATA_SRC pointed
# them at whatever tree the build ran from, so a build from a git worktree left
# data.compute.tech with two dangling links and no stats at all. Pin them to the
# canonical path, the way SHARD_SRC already is.
ln -sfn "$LIVE_DATA/stats.json"   "$OUT/data/stats.json"
ln -sfn "$LIVE_DATA/network.json" "$OUT/data/network.json"

# ── shard.compute.tech ───────────────────────────────────────────────────────
echo "==> shard"
python3 "$REBRAND" "$SHARD_SRC" "$OUT/shard"
ln -sfn "$SHARD_SRC/network.json" "$OUT/shard/network.json"

# ── the mark, at every site root ─────────────────────────────────────────────
# The rebrand pass rewrites each site's favicon href to /favicon.svg; this puts
# the file there. Same mark on the app, the docs and all three static sites, so
# a reader moving between them never sees the tab icon change identity.
#
# The .ico goes beside it because declaring the SVG is not enough: browsers ask
# for /favicon.ico at the site root regardless of what the page declares, and
# prefer it to the declared link. On the app that request was answered by
# public/favicon.ico — the legacy c0mpute mark, which cannot change, c0mpute.ai
# being the same Next deployment — so compute.tech kept showing the old icon
# however the <link> was written. The copy at the tree root is what the
# compute.tech server block aliases for the app; the four in the site roots are
# found by each block's existing try_files, no nginx change needed.
echo "==> favicon"
cp "$REPO/public/brand/favicon.ico" "$OUT/favicon.ico"
for d in docs blog data shard; do
  cp "$REPO/public/brand/favicon.svg" "$OUT/$d/favicon.svg"
  cp "$REPO/public/brand/favicon.ico" "$OUT/$d/favicon.ico"
done
# Docusaurus copies docs-site/static/img/ into its build, and that favicon.ico is
# still the legacy mark — docs.c0mpute.ai declares it by name, so the source file
# has to stay exactly as it is. Overwrite it in the generated tree only, so that
# no legacy icon is reachable anywhere under compute.tech.
cp "$REPO/public/brand/favicon.ico" "$OUT/docs/img/favicon.ico"

# ── cache-bust the local assets ──────────────────────────────────────────────
# Cloudflare caches these for 4 hours, so a rebuild that changes a file keeps
# serving the old one until the TTL lapses — which is exactly how a theme change
# appears not to work. It bit twice: once on style.css, then again on app.js,
# which carries the chart's colours. Stamping every locally-referenced css and
# js with a hash of its contents means a changed file is a different URL and can
# never be served stale; an unchanged one keeps its cache.
echo "==> cache-bust"
python3 - "$OUT" <<'PYBUST'
import hashlib, pathlib, re, sys
out = pathlib.Path(sys.argv[1])
for d in ('blog', 'data', 'shard'):
    root = out / d
    if not root.is_dir():
        continue
    digests = {
        f.name: hashlib.md5(f.read_bytes()).hexdigest()[:8]
        for f in root.iterdir()
        if f.suffix in ('.css', '.js') and f.is_file()
    }
    if not digests:
        continue
    names = sorted(digests, key=len, reverse=True)
    pat = re.compile(
        r'((?:href|src)=")([^"]*?(?:' + '|'.join(re.escape(n) for n in names) + r'))(?:\?v=[a-f0-9]+)?(")'
    )
    def stamp(m):
        name = next(n for n in names if m.group(2).endswith(n))
        return f'{m.group(1)}{m.group(2)}?v={digests[name]}{m.group(3)}'
    for html in root.rglob('*.html'):
        text = html.read_text()
        new = pat.sub(stamp, text)
        if new != text:
            html.write_text(new)
PYBUST

echo "==> done: $OUT"
