#!/usr/bin/env bash
# state-sync.sh — regenerate c0mpute/STATE.md from LIVE signals.
# Read-only. Pulls git, systemd, env flags, on-chain ($ZERO), treasury, keeper.
# Run manually or via timer/post-commit hook. Source of truth for "what's live".
set -uo pipefail

ROOT="/root/.openclaw/workspace/c0mpute"
OUT="$ROOT/STATE.md"
cd "$ROOT" || exit 1

# load env (names+values) without leaking secrets into output
get() { grep -E "^$1=" .env.local 2>/dev/null | head -1 | cut -d= -f2-; }
isset() { [ -n "$(get "$1")" ] && echo "set" || echo "EMPTY"; }

ZERO_MINT="$(get ZERO_TOKEN_MINT)"
TRACKER_KEY="$(get SOLANA_TRACKER_API_KEY)"
NOW="$(date -u '+%Y-%m-%d %H:%M UTC')"

# --- git ---
GIT_HEAD="$(git log -1 --format='%h %ci %s' 2>/dev/null)"
GIT_SYNC="$(git rev-list --left-right --count origin/master...HEAD 2>/dev/null)"  # behind  ahead
GIT_DIRTY="$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')"

# --- services ---
svc() { systemctl is-active "$1" 2>/dev/null; }

# --- on-chain $ZERO ---
ZERO_MARKET="n/a"; ZERO_MCAP="n/a"; ZERO_LIQ="n/a"; ZERO_PRICE="n/a"; ZERO_CHG="n/a"
if [ -n "$ZERO_MINT" ] && [ -n "$TRACKER_KEY" ]; then
  ZERO_LINE="$(curl -s --max-time 15 "https://data.solanatracker.io/tokens/$ZERO_MINT" -H "x-api-key: $TRACKER_KEY" \
    | python3 -c "import sys,json
try:
 d=json.load(sys.stdin); p=(d.get('pools') or [{}])[0]
 mc=p.get('marketCap',{}).get('usd') or 0; lq=p.get('liquidity',{}).get('usd') or 0
 pr=p.get('price',{}).get('usd'); ch=d.get('events',{}).get('24h',{}).get('priceChangePercentage') or 0
 print('|'.join([str(p.get('market')), str(round(mc)), str(round(lq)), str(pr), str(round(ch,1))]))
except Exception: print('n/a|n/a|n/a|n/a|n/a')" 2>/dev/null)"
  IFS='|' read -r ZERO_MARKET ZERO_MCAP ZERO_LIQ ZERO_PRICE ZERO_CHG <<< "$ZERO_LINE"
fi

# --- treasury (lifetime stats) ---
TRE="$(curl -s --max-time 15 https://c0mpute.ai/api/treasury 2>/dev/null)"
tfield() { echo "$TRE" | python3 -c "import sys,json;
try: print(json.load(sys.stdin).get('$1','n/a'))
except Exception: print('n/a')" 2>/dev/null; }

# --- keeper last cycle ---
KEEPER_LAST="$(journalctl -u c0mpute-keeper --no-pager -n 200 2>/dev/null | grep -E 'Cycle (start|complete)|Bought \+ burned|Distributed' | tail -4)"
KEEPER_DRY="$(systemctl show c0mpute-keeper -p Environment 2>/dev/null | grep -o 'KEEPER_DRY_RUN=[a-z]*')"

# --- public API liveness ---
API_MODELS="$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 https://c0mpute.ai/api/v1/models)"

# --- comfy tunnel ---
COMFY_STATE="$(svc c0mpute-comfy-tunnel)"

cat > "$OUT" <<EOF
# c0mpute — LIVE STATE (auto-generated)

> Generated by \`scripts/state-sync.sh\` at **$NOW**. Do not hand-edit — it gets overwritten.
> This is the single source of truth for what is actually live. Re-run the script to refresh.

## Code / Git
- HEAD: \`$GIT_HEAD\`
- origin/master sync (behind / ahead): \`$GIT_SYNC\`
- uncommitted working-tree entries: **$GIT_DIRTY**

## Services (systemd)
- web (c0mpute.ai): **$(svc c0mpute-web)**
- orchestrator (:3004): **$(svc c0mpute-orchestrator)**
- keeper (buyback/staking): **$(svc c0mpute-keeper)**  [$KEEPER_DRY]
- comfy tunnel (image gen GPU): **$COMFY_STATE**

## Public API
- \`GET /api/v1/models\` → HTTP **$API_MODELS** (401 = live+auth-enforced; 000/5xx = down)

## \$ZERO token
- launched: **$(tfield launched)**
- mint: \`$ZERO_MINT\`
- market: $ZERO_MARKET  |  mcap \$$ZERO_MCAP  |  liq \$$ZERO_LIQ
- price: \$$ZERO_PRICE  |  24h: $ZERO_CHG%

## Treasury (lifetime, from /api/treasury)
- total ZERO burned: $(tfield totalZeroBurned)
- total USD buyback spent: \$$(tfield totalUsdBuybackSpent)
- total staker rewards paid: \$$(tfield totalStakerRewardsPaid)
- total ZERO staked: $(tfield totalStaked)
- pending buyback: \$$(tfield pendingBuyback)  |  pending staker rewards: \$$(tfield pendingStakerRewards)

## Keeper — recent cycle log
\`\`\`
$KEEPER_LAST
\`\`\`

## Env flags (presence only, no secrets)
- ZERO_TOKEN_MINT: $(isset ZERO_TOKEN_MINT)
- TREASURY_WALLET_KEY: $(isset TREASURY_WALLET_KEY)
- PUMP_DEV_WALLET_KEY: $(isset PUMP_DEV_WALLET_KEY)
- INTERNAL_API_SECRET: $(isset INTERNAL_API_SECRET)
- DEPOSIT_WALLET_KEY: $(isset DEPOSIT_WALLET_KEY)
- COMFY_URL: $(get COMFY_URL)  |  COMFY_CKPT: $(get COMFY_CKPT)
EOF

echo "wrote $OUT at $NOW"
