import SiteNav from '@/components/SiteNav';
import SiteFooter from '@/components/SiteFooter';
import NetworkGlobe from '@/components/network/NetworkGlobe';
import NetworkIndex from '@/components/network/NetworkIndex';
import TreasuryPanel from '@/components/treasury/TreasuryPanel';
import { pageMetadata } from '@/lib/seo';
import './network.css';

// /network: the live map, usage, treasury, $ZERO and how it works as one
// top-to-bottom story. Every figure is live: the globe polls the shard map feed,
// usage is the data site's stats.json (fetched here, refreshed every 60s) and
// the treasury block is the same component /treasury renders.
export const revalidate = 60;

export const generateMetadata = () =>
  pageMetadata({
    title: 'Network',
    description: 'A live globe of scattered consumer GPUs serving one model together.',
    path: '/network',
  });

interface Stats {
  live?: { workersOnline: number; byType: { native: number; browser: number; image: number }; busy: number };
  network?: { totals?: { tokens?: number }; jobsDaily?: { day: string; tier: string; jobs: number }[] };
}

async function getStats(): Promise<Stats | null> {
  try {
    const r = await fetch('https://data.compute.tech/stats.json', { next: { revalidate: 60 } });
    return r.ok ? ((await r.json()) as Stats) : null;
  } catch {
    return null;
  }
}

const comma = (n: number) => Math.round(n).toLocaleString('en-US');
const D = <span className="dollar">$</span>;

// last 30 UTC days of jobs, split the way the data site splits them: stored
// tiers 'max'/'pro' are the native and browser lanes
function jobsByDay(rows: { day: string; tier: string; jobs: number }[]) {
  const days: string[] = [];
  for (let i = 29; i >= 0; i--) days.push(new Date(Date.now() - i * 864e5).toISOString().slice(0, 10));
  const m: Record<string, number> = {};
  for (const r of rows) m[`${r.day}|${r.tier}`] = (m[`${r.day}|${r.tier}`] || 0) + (r.jobs || 0);
  return days.map((d) => {
    const native = m[`${d}|max`] || 0, browser = m[`${d}|pro`] || 0, image = m[`${d}|image`] || 0;
    return { d, native, browser, image, total: native + browser + image };
  });
}

function Eyebrow({ n, t, night }: { n: string; t: React.ReactNode; night?: boolean }) {
  return <p className={`nw-eyebrow${night ? ' night' : ''}`}><span className="n">{n}</span><span>{t}</span></p>;
}

export default async function NetworkPage() {
  const stats = await getStats();
  const lv = stats?.live;
  const jobs = stats?.network?.jobsDaily ? jobsByDay(stats.network.jobsDaily) : [];
  const maxJobs = Math.max(1, ...jobs.map((j) => j.total));

  return (
    <div className="nw min-h-screen bg-background">
      <SiteNav />
      <div className="nw-top" />
      <NetworkIndex />

      {/* 01 Live: the night ground with the globe */}
      <section id="live" className="nw-hero">
        <div className="nw-hero-head">
          <Eyebrow n="01" t="Live" night />
          <h1>Network</h1>
        </div>
        <NetworkGlobe />
      </section>

      {/* 02 Usage */}
      <section id="usage" className="nw-sec">
        <div className="nw-in">
          <Eyebrow n="02" t="Usage" />
          {stats ? (
            <>
              <h2 className="nw-big">{comma(stats.network?.totals?.tokens || 0)}</h2>
              <p className="nw-big-k">tokens generated by the network</p>
              {lv && (
                <div className="nw-cards">
                  {[
                    { v: lv.workersOnline, k: 'workers online' },
                    { v: lv.byType.native, k: 'native (gpu)' },
                    { v: lv.byType.browser, k: 'browser' },
                    { v: lv.byType.image, k: 'image' },
                    { v: <>{lv.busy}<small>/{lv.workersOnline}</small></>, k: 'busy now' },
                  ].map((c) => (
                    <div key={c.k} className="nw-card"><div className="v">{c.v}</div><div className="k">{c.k}</div></div>
                  ))}
                </div>
              )}
              {jobs.length > 0 && (
                <div className="nw-chart">
                  <div className="nw-chart-head">
                    <span>Jobs per day, last 30 days</span>
                    <span className="nw-legend"><i className="s1" />native <i className="s2" />browser <i className="s3" />image</span>
                  </div>
                  <div className="nw-bars" role="img" aria-label="Jobs per day over the last 30 days">
                    {jobs.map((j) => (
                      <div key={j.d} className="nw-bar" title={`${j.d}\nnative: ${comma(j.native)}\nbrowser: ${comma(j.browser)}\nimage: ${comma(j.image)}\ntotal: ${comma(j.total)}`}>
                        <i className="s3" style={{ height: `${(j.image / maxJobs) * 100}%` }} />
                        <i className="s2" style={{ height: `${(j.browser / maxJobs) * 100}%` }} />
                        <i className="s1" style={{ height: `${(j.native / maxJobs) * 100}%` }} />
                      </div>
                    ))}
                  </div>
                  <div className="nw-chart-foot"><span>{jobs[0].d}</span><span>max {comma(maxJobs)}</span><span>{jobs[jobs.length - 1].d}</span></div>
                </div>
              )}
            </>
          ) : (
            <p className="nw-body">Usage data could not be loaded. This section refreshes every minute.</p>
          )}
        </div>
      </section>

      {/* 03 Treasury: the same component /treasury renders */}
      <section id="treasury" className="nw-sec">
        <div className="nw-in">
          <Eyebrow n="03" t="Treasury" />
          <h2 className="nw-h">Treasury</h2>
          <p className="nw-body">
            The compute margin and a share of {D}ZERO trading fees accumulate here.
            Half buys back and burns {D}ZERO; half is paid to stakers in {D}USDC.
          </p>
          <div className="nw-treasury">
            <TreasuryPanel />
          </div>
        </div>
      </section>

      {/* 04 $ZERO: copy from docs/zero-token.md and the staking cross-link */}
      <section id="zero" className="nw-sec">
        <div className="nw-in nw-split">
          <div>
            <Eyebrow n="04" t={<>{D}ZERO</>} />
            <h2 className="nw-h">The {D}ZERO Token</h2>
            <p className="nw-body">
              {D}ZERO is how the value the network creates flows back to the people who hold and stake it.
            </p>
            <a href="/staking" className="nw-btn"><span>Stake {D}ZERO</span></a>
          </div>
          <ul className="nw-list">
            <li><b>Use Compute Network</b><span>pay in USDC</span></li>
            <li><b>Hold {D}ZERO</b><span>benefit from buybacks and burns as the network grows</span></li>
            <li><b>Stake {D}ZERO</b><span>earn a share of network revenue in USDC and get a daily free-credit allowance</span></li>
          </ul>
        </div>
      </section>

      {/* 05 How it works: condensed from docs/how-it-works.md and architecture.md */}
      <section id="how" className="nw-sec">
        <div className="nw-in nw-split">
          <div>
            <Eyebrow n="05" t="How it works" />
            <h2 className="nw-h">How Compute Network works</h2>
            <p className="nw-flow">User → Orchestrator → Worker → tokens stream back → User</p>
            <div className="nw-acts">
              <a href="https://docs.compute.tech" target="_blank" rel="noopener noreferrer">Docs</a>
              <a href="https://docs.compute.tech/architecture" target="_blank" rel="noopener noreferrer">Architecture</a>
              <a href="https://github.com/leyten/shard" target="_blank" rel="noopener noreferrer">GitHub</a>
            </div>
          </div>
          <ol className="nw-list nw-steps">
            <li><b>01</b><span>The orchestrator receives your request and finds a worker that serves the model it needs.</span></li>
            <li><b>02</b><span>The worker runs inference on their GPU and streams tokens back through the orchestrator.</span></li>
            <li><b>03</b><span>The orchestrator does not store conversations. It routes traffic and moves on.</span></li>
          </ol>
        </div>
      </section>

      <SiteFooter />
    </div>
  );
}
