var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/staking-onchain/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__5ea3dff5._.js")
R.c("server/chunks/ssr/_71ee9283._.js")
R.c("server/chunks/ssr/_9c31f0b7._.js")
R.c("server/chunks/ssr/_472c1382._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e869bc6f._.js")
R.c("server/chunks/ssr/node_modules_next_eb8ce55b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_81959fb0._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__179ac700._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_staking-onchain_page_actions_d4039677.js")
R.m(606930)
module.exports=R.m(606930).exports
