var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/profile/route.js")
R.c("server/chunks/[root-of-the-server]__2af6c9e7._.js")
R.c("server/chunks/lib_db_ts_033a32e3._.js")
R.c("server/chunks/node_modules_node-fetch-native_dist_node_mjs_558d0a9c._.js")
R.c("server/chunks/node_modules_@noble_curves_8b603fa7._.js")
R.c("server/chunks/[root-of-the-server]__98d6514a._.js")
R.c("server/chunks/_d08b9ff6._.js")
R.c("server/chunks/node_modules_eb70c2c4._.js")
R.c("server/chunks/[root-of-the-server]__f408c708._.js")
R.c("server/chunks/_next-internal_server_app_api_profile_route_actions_0369ef5c.js")
R.m(809303)
module.exports=R.m(809303).exports
